### ISSUE TITLE
[WEB] [IMPROVEMENT] Improve Editor

### ISSUE THREAD

**Issue by Himasnhu-AT** [Himasnhu-AT/noterAI#56]
in `apps/web` we have an editor. so if you visit "/editor", you can view it. right now the UI isn't that great, so try to improve the UI and make it work as expected.

**Comment by Himasnhu-AT** [comment]
For letting cool off time for servers, as specified in #57 , do this:

only make webhook calls after a certain amount of time ( 1 min, or 30 seconds), or the user presses `command+s` or `ctrl+s`.

After migrating the editor to `packages/'@noterai-editor'`


## How we will import `@noterai-editor`?

```tsx

interface NoterEditorConfig {
    server: string
    feature_level: boolean | object  // true mean all, false mean none, and object will specify each object seperately
    shortcuts: boolean | object // same as above
}

// config
const config: NoterEditorConfig = {
    "server": "localhost:3000",
    "feature_level": "all",
    "shortcuts": true
}

< NoterEditor(config) />
```

**Comment by Neel-07** [comment]
can this issue be assigned to me 
@Himasnhu-AT

**Comment by Himasnhu-AT** [comment]
Okay, assigning it to you. Here's what you need to do:

- when we visit /editor, the UI isn't great. Following the schema that we used, I need you to update the /editor route to look somewhat similar to notion.

Ensure you write most of the code yourself, and the code isn't taken from some source that have it licensed.

Also, can you provide me approx time for its completion?

**Comment by Neel-07** [comment]
@Himasnhu-AT  will be implementing notion like editor on to it.  i can complete it within tomorrow if it is fine

**Comment by Himasnhu-AT** [comment]
@Neel-07 Any progress on it?

**Comment by Himasnhu-AT** [comment]
Made branch `editor` for it, push you commits in it, and lemme know if you need any help rn

**Comment by Neel-07** [comment]
hello @Himasnhu-AT  having some issue to move to editor page if you can specify the exact route it would be helpful. As the signin and signup auth pages are not fully functional so having issues.

**Comment by Himasnhu-AT** [comment]
@Neel-07 

It's `/editor` url. If you go to folder: `app/editor/page.tsx` you can view the file.

**Comment by Neel-07** [comment]
@Himasnhu-AT  just got to see it, i did the go to the route /editor but it was showing Loading...  whenever i opened, then deleted the project from local system, again cloned in local system then the editor.tsx component was rendered

**Comment by Himasnhu-AT** [comment]
> @Himasnhu-AT just go to see it

Didn't understand?

**Comment by Neel-07** [comment]
@Himasnhu-AT 

https://github.com/user-attachments/assets/e9c15de8-bbb3-4f84-bc84-dbea05437541

is the implementation of the editor fine

**Comment by Himasnhu-AT** [comment]
@Neel-07 Looks awsm 👍

**Comment by Neel-07** [comment]
@Himasnhu-AT  can we collaborate for this project, like for web part i think i can contribute more to it, so if there is discord server where we can discuss things it would be really great.
