### ISSUE TITLE
navbar is broken [WEB]

### ISSUE THREAD

**Issue by krish858** [Himasnhu-AT/noterAI#65]
![ksnip_20241020-140437](https://github.com/user-attachments/assets/9c4c1422-7861-4d63-8172-88bb240644c3)
![ksnip_20241020-140510](https://github.com/user-attachments/assets/4d9b9103-93b0-444f-84e9-37cc8e763234)

**Comment by Himasnhu-AT** [comment]
hi @krish858  , thanks for pr, but its already implemented / modified in branch dem_pages
